package br.ifce.edu.ppd.commons.util;

public enum Operations {
	ADD_ROOM,
	REMOVE_ROOM,
	ADD_CLIENT_IN_ROOM,
	REMOVE_CLIENT_FROM_ROOM,
	START_SERVER,
	STOP_SERVER,
	CLIENT_CONNECTED,
	CLIENT_DISCONNECTED
}
